### ISSUE TITLE
This image is not available

### ISSUE THREAD

**Issue by ahawkins** [CircleCI-Public/cimg-redis#2]
```
git:main >> docker pull cimg/redis
Using default tag: latest
Error response from daemon: manifest for cimg/redis:latest not found: manifest unknown: manifest unknown
```

All docs point to this image being available but it's not.

**Comment by BytesGuy** [comment]
@ahawkins Hi, we do not publish `latest` tags for any of the new `cimg` images. You will need specify a version to pull. The list of tags can be found on Dockerhub (these will be included in the CircleCI Developer Hub once the image reaches RC status)

https://hub.docker.com/r/cimg/redis/tags

**Comment by BytesGuy** [comment]
I'll close this issue out, but feel free to re-open it if you have any issues pulling the tags listed in Dockerhub. Thanks!
