### ISSUE TITLE
Starting redis in cluster mode

### ISSUE THREAD

**Issue by ayang-rkjs** [CircleCI-Public/cimg-redis#8]
Hello,

Thanks for publishing and maintaining this incredibly useful docker image! My team uses it to easily spin up Redis for running integration tests in our CircleCI pipeline.

One feature that we'd love to have is the ability to configure some setting on the redis, in particular enabling redis cluster mode. I saw that in cimg-mysql you're able to set some ENV variable for passwords and stuff. Maybe we could add some ENV variables for setting the redis port, enabling cluster mode, etc.

I'm not an expert with Dockerfiles but I thought maybe we could implement this by adding ENV variables to the Dockerfile like REDIS_PORT, CLUSTER_MODE_ENABLED, adding a RUN step that uses those variable to generate a redis.conf, and then calling the redis-server command with our redis.conf passed.

What do you think?

**Comment by JalexChen** [comment]
Hi @ayang-rkjs

Convenience Images are meant to come with everything you need to run a build on CircleCI. Your specific use case doesn't necessitate a change to the actual image and is more suited to the configuration level, which is done through the config.yml.

If passwords and other sensitive information is being passed through, I would recommend either using a Context [docs here](https://circleci.com/docs/2.0/contexts/) or project level environment variables - both of which can be accessed through CircleCI's app, and provide you with the functionality you are describing. 

At the moment, we don't have a Redis Orb, which could simplify the configurations you're talking about, but could potentially be built out in the future.

**Comment by felicianotech** [comment]
@BytesGuy Since you created this image, do you have an idea for a starting point for such a request?

**Comment by felicianotech** [comment]
Pinged him on Slack.

**Comment by felicianotech** [comment]
This is not something we have planned at the moment.
